export type LegalSection = { title: string; paragraphs: string[] };

export const LEGAL_UPDATED_AT = '20 juillet 2026';

export const privacySections: LegalSection[] = [
  { title: '1. Responsable', paragraphs: ['Fragmenta est exploité par Jean-Michel Tremblay, responsable de la protection des renseignements personnels. Pour une question, une demande d’accès, de rectification, de retrait du consentement ou une plainte : jmturbex@fragmenta.ca, 373 boulevard des Laurentides, Laval (Québec) H7G 2T9.'] },
  { title: '2. Renseignements recueillis', paragraphs: ['Nous pouvons recueillir les renseignements fournis lors de la création et de la gestion du compte : adresse courriel, nom affiché, nom d’utilisateur, biographie, pays, avatar et liens sociaux.', 'Lorsque tu utilises les fonctions de publication, nous traitons le contenu soumis, notamment les aventures, fragments, curiosités, textes, photos, dates, catégories, emplacements, coordonnées géographiques et renseignements d’accessibilité.', 'Nous conservons aussi les données nécessaires aux favoris, blocages, signalements, demandes de vérification, actions de modération, sécurité et fonctionnement technique.'] },
  { title: '3. Finalités', paragraphs: ['Ces renseignements servent à créer et sécuriser ton compte, afficher et distribuer tes publications selon leur visibilité, fournir la carte et les itinéraires, personnaliser ton expérience, traiter les signalements, modérer la plateforme, répondre aux demandes et améliorer la fiabilité du service.'] },
  { title: '4. Géolocalisation', paragraphs: ['La localisation de l’appareil n’est utilisée qu’après permission. Elle sert à afficher ta position, choisir un emplacement ou calculer un contexte géographique. Une position ajoutée à une publication publique peut révéler un lieu précis. Évite de publier ton domicile ou un endroit sensible. Tu peux retirer la permission dans les réglages de ton appareil.'] },
  { title: '5. Visibilité et communications', paragraphs: ['Les profils publics et les publications publiques peuvent être consultés par d’autres utilisateurs. Les fournisseurs techniques nécessaires, notamment Supabase et les services d’hébergement, peuvent traiter des renseignements pour fournir le service. Nous ne vendons pas tes renseignements personnels.', 'Une communication hors Québec doit être encadrée conformément aux lois applicables et aux ententes avec les fournisseurs concernés.'] },
  { title: '6. Conservation et sécurité', paragraphs: ['Les renseignements sont conservés aussi longtemps que nécessaire aux finalités décrites, au respect de nos obligations et à la résolution des incidents. Des mesures raisonnables de sécurité, des contrôles d’accès et des politiques Supabase protègent les données, sans qu’aucun système puisse garantir une sécurité absolue.'] },
  { title: '7. Tes choix et tes droits', paragraphs: ['Tu peux modifier ton profil, exporter tes données et supprimer ton compte depuis l’application. Tu peux aussi demander l’accès, la rectification ou poser une question au responsable. La suppression du compte est définitive et entraîne la suppression des données associées, sous réserve des obligations légales applicables.'] },
  { title: '8. Âge minimal', paragraphs: ['Il faut avoir au moins 18 ans pour créer un compte Fragmenta. Nous pouvons suspendre ou supprimer un compte si nous avons des motifs raisonnables de croire que cette condition n’est pas respectée.'] },
  { title: '9. Liens et services externes', paragraphs: ['Les liens sociaux, cartes, itinéraires et services externes sont régis par les politiques de leurs exploitants. Fragmenta n’est pas responsable de leurs pratiques.'] },
  { title: '10. Modifications et plaintes', paragraphs: ['Nous pouvons mettre à jour cette politique lorsque le service ou les exigences changent. Une modification importante sera portée à l’attention des utilisateurs par un moyen approprié. Toute plainte peut être envoyée au responsable aux coordonnées indiquées ci-dessus.'] },
];

export const termsSections: LegalSection[] = [
  { title: '1. Acceptation', paragraphs: ['En créant un compte ou en utilisant Fragmenta, tu acceptes les présentes conditions. Si tu ne les acceptes pas, n’utilise pas le service.'] },
  { title: '2. Admissibilité', paragraphs: ['Tu dois avoir au moins 18 ans pour créer un compte. Tu dois fournir des renseignements exacts, protéger ton mot de passe et nous informer rapidement de toute utilisation non autorisée.'] },
  { title: '3. Description du service', paragraphs: ['Fragmenta permet de découvrir, créer et partager des aventures, fragments, curiosités, photos et emplacements. Certaines fonctions peuvent être modifiées, suspendues ou retirées pendant le développement et l’exploitation du service.'] },
  { title: '4. Sécurité des aventures', paragraphs: ['Tu demeures responsable de tes déplacements, de ta préparation et de l’évaluation des risques. Les cartes, coordonnées, itinéraires, renseignements d’accessibilité et descriptions sont fournis à titre informatif et peuvent être inexacts, incomplets ou périmés. Respecte la propriété privée, les lois, les fermetures, les conditions météorologiques et les consignes des autorités.'] },
  { title: '5. Contenu des utilisateurs', paragraphs: ['Tu conserves tes droits sur ton contenu. Tu accordes à Fragmenta une licence mondiale, non exclusive et sans redevance pour héberger, reproduire, adapter techniquement et afficher ce contenu uniquement afin d’exploiter, promouvoir et améliorer le service, jusqu’à sa suppression sous réserve des copies de sécurité raisonnables.', 'Tu confirmes posséder les droits nécessaires et les autorisations des personnes reconnaissables. Ne publie pas de renseignements sensibles, de position privée ou de contenu qui met quelqu’un en danger.'] },
  { title: '6. Conduite interdite', paragraphs: ['Il est interdit de publier du contenu illégal, trompeur, haineux, harcelant, sexuel non consenti, exploitant des mineurs, violent ou dangereux; d’usurper une identité; de menacer autrui; de contourner la sécurité; de collecter des données sans autorisation; ou d’utiliser Fragmenta pour organiser une activité illégale.'] },
  { title: '7. Modération', paragraphs: ['Nous pouvons vérifier, limiter, masquer ou supprimer du contenu et suspendre ou fermer un compte pour protéger les utilisateurs, appliquer ces conditions ou respecter la loi. Les signalements et décisions peuvent être consignés. La vérification d’une curiosité ne garantit pas sa sécurité, son accessibilité ni son exactitude permanente.'] },
  { title: '8. Propriété intellectuelle', paragraphs: ['Fragmenta, son identité, son interface et son code sont protégés par les lois applicables. Aucun droit sur ces éléments ne t’est transféré, sauf le droit limité d’utiliser le service conformément aux présentes conditions.'] },
  { title: '9. Services externes', paragraphs: ['Fragmenta peut ouvrir des cartes, itinéraires, sites et réseaux sociaux externes. Leur disponibilité, leur contenu et leurs pratiques relèvent de leurs exploitants.'] },
  { title: '10. Disponibilité et responsabilité', paragraphs: ['Le service est fourni selon sa disponibilité. Dans les limites permises par la loi, Fragmenta ne garantit pas une disponibilité continue ni l’exactitude de tout contenu communautaire et n’est pas responsable des décisions de déplacement prises à partir du service. Rien dans ces conditions ne limite un droit ou une garantie qui ne peut légalement être exclu.'] },
  { title: '11. Fin du compte', paragraphs: ['Tu peux supprimer ton compte dans l’application. Nous pouvons suspendre ou fermer un compte en cas de violation, de risque pour la communauté ou d’obligation légale. Les dispositions qui doivent raisonnablement survivre continuent de s’appliquer.'] },
  { title: '12. Droit applicable et contact', paragraphs: ['Les présentes conditions sont régies par les lois applicables au Québec et au Canada, sans retirer les protections impératives dont bénéficie un consommateur. Pour communiquer avec Fragmenta : Jean-Michel Tremblay, jmturbex@fragmenta.ca, 373 boulevard des Laurentides, Laval (Québec) H7G 2T9.'] },
];
